config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]

  get 'angular-items', to: "portfolios#angular_items"
  get 'ror-items', to: "portfolios#ror_items"
  get 'portfolio/:id',to: "portfolios#show", as: "portfolio_show"

  # post 'toggle_blog_status/:id', to: "blogs#toggle_status", as: 'toggle_blog_status'

  resources :blogs do
    member do
      post :toggle_status
    end
  end
  devise_for :users

  #get 'something/about'
  get 'admin_dashboard', to: "pages#admin_dashboard"
  get 'about', to: 'pages#about'
  get 'contact', to:'pages#contact'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title,:body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
# frozen_string_literal: false

module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: ->(attributes) { attributes['name'].blank? }
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular_items
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_items, -> { where(subtitle: 'Ruby on rails') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 250, width: 200)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized
  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: 250, width: 250)
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog status was successfully updated." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :string, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #before_action :authenticate_user!, except: [:home]
  def home
    @skills = Skill.all
  end

  def admin_dashboard
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  def index
    @portfolio_items = Portfolio.all
  end

  def angular_items
    @portfolio_items = Portfolio.angular_items
    render 'index'
  end

  def ror_items
    @portfolio_items = Portfolio.ruby_on_rails_items
    render 'index'
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully created." }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: "portfolio was successfully updated." }

      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html {redirect_to portfolios_path, notice: "Portfolio was successfully destroyed."}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end
end

app/controllers/something_controller.rb
class SomethingController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/something_helper.rb
module SomethingHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>String</th>
      <th>Body</th>
      <th> Blog Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.string %></td>
        <td><%= blog.body %></td>
        <td> <%=link_to blog.status,toggle_status_blog_path(blog), method: 'post' %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>String:</strong>
  <%= @blog.string %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails6Tryout</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/admin_dashboard.html.erb
<h1>Admin page </h1>

app/views/pages/contact.html.erb
<h1>Contact us </h1>

app/views/pages/home.html.erb
<h1> Home page</h1>
<h1>Skills</h1>
<%=  @skills.inspect %>
<% if current_user%>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
 <%else%>
  <%= link_to "Login", new_user_session_path%>
  <%= link_to "Register", new_user_registration_path%>
 <%end%>

app/views/portfolios/edit.html.erb
<h1>Edit new Portfolio</h1>
<%= form_with(model: @portfolio) do |form| %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items </h1>
<table>
  <thead>
      <tr>
        <th>Title</th>
        <th>Subtitle</th>
        <th>Body</th>
        <th >Thumb Image</th>
        <th colspan ="2">Action</th>
      </tr>
  </thead>
  <tbody>
      <% @portfolio_items.each do |item| %>
      <tr>
        <td><%= link_to item.title, portfolio_show_path(item)%></td>
        <td><%= item.subtitle%></td>
        <td><%= item.body%></td>
        <td><%= image_tag item.thumb_image unless item.thumb_image.nil?%></td>

        <td><%= link_to "Edit", edit_portfolio_path(item)%></td>
        <td><%= link_to "Destroy", item, method: :delete,data: { confirm: 'Are you sure?' }%></td>
      <% end %>
    </tr>
  </tbody>
</table>
<%= link_to "Create New Portfolio", new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>Create new Portfolio</h1>
<%= form_with(model: @portfolio) do |form| %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @portfolio.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @portfolio.subtitle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @portfolio.body %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>

app/views/something/about.html.erb
<h1>Something about us</h1>
<p>Find me in app/views/something/about.html.erb</p>